### ISSUE TITLE
Provide a working example for MongoDb Atlas

### ISSUE THREAD

**Issue by UNOPARATOR** [node-red-tools/node-red-contrib-mongodb#18]
Please provide a working example configuration for using your node with a MongoDb Atlas connection. I tried everything that I could think of but nothing was successful.

**Comment by ziflex** [comment]
Hey, I haven't used this plugin with MongoDB Atlas. 
What issues are you experiencing ?

**Comment by UNOPARATOR** [comment]
MongoDb Atlas gives me this connection string which I can use with MongoDb Compass without any problems:
```
mongodb+srv://loader:<pasword>@my_hidden_host_name.azure.mongodb.net/testDB?authSource=admin&retryWrites=true&w=majority
```
Here is my mongodb-config node info:
![image](https://user-images.githubusercontent.com/1214176/79110686-a6bfd900-7d83-11ea-8a5a-32f08b362649.png)
![image](https://user-images.githubusercontent.com/1214176/79110703-b17a6e00-7d83-11ea-84e2-82ef08131023.png)
I tried with and without specifying options
![image](https://user-images.githubusercontent.com/1214176/79110726-bb9c6c80-7d83-11ea-890f-58e515cdd608.png)

And here is my collection node info:
![image](https://user-images.githubusercontent.com/1214176/79110800-e1297600-7d83-11ea-9563-7e7677990e86.png)
This is the error message shown in debug window:
> MongoServerSelectionError: getaddrinfo ENOTFOUND my_hidden_host_name.azure.mongodb.net my_hidden_host_name.azure.mongodb.net:27017    at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (/data/node_modules/mongodb/lib/core/sdam/topology.js:430:30)    at ontimeout (timers.js:436:11)    at tryOnTimeout (timers.js:300:5)    at listOnTimeout (timers.js:263:5)    at Timer.processTimers (timers.js:223:10)

**Comment by ziflex** [comment]
I think ``mongodb+srv://`` this is the key.
We need to add a support of it as it says [here](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format).
Could you make a small change in your local copy of the package?
Replace ``mongodb://`` with just ``mongo`` [right here](https://github.com/node-red-tools/node-red-contrib-mongodb/blob/master/src/core/settings.ts#L4) and update your connection string accordingly.

**Comment by UNOPARATOR** [comment]
That doesn't work either (even if I replace `mongodb://` with `mongo://`), but changing the `mongodb://` with `mongodb+srv://` does work.

You might take the following as a suggestion or not, it is up to you:
I think you'll need to handle both cases in your code, or toggle `+srv` with a checkbox or something.
Alternatively you might give an option to set the connection either via a connection string textbox or via seperate input controls (just like now). Just my two cents.

**P.S:** You can always create a free (M0 tier) MongoDb Atlas instance to test it further. ;)

**Comment by ziflex** [comment]
@UNOPARATOR hey, can you try this fix to make sure it solved your problem? 
https://github.com/node-red-tools/node-red-contrib-mongodb/tree/bugfix/%2318-atlas

**Comment by UNOPARATOR** [comment]
I converted the settings.ts file to settings.js using [an online converter](https://www.typescriptlang.org/play) then restarted my Node-RED instance. It works, thank you 💯

**Comment by ziflex** [comment]
Published a new 1.3.0 version .

**Comment by UNOPARATOR** [comment]
Just a heads up, it is still not showing up on [Node-RED's site](https://flows.nodered.org/node/@node-red-tools/node-red-contrib-mongodb) or as an update in Node-RED's admin ui.

**Comment by ziflex** [comment]
It is now. Seems there is a delay.

**Comment by UNOPARATOR** [comment]
Another just a heads up. ;)
Unfortunately after all this time, it still shows the v1.2.0 as the latest version at https://flows.nodered.org/node/@node-red-tools/node-red-contrib-mongodb , which makes it impossible to update using the "Manage palette" menu.
![image](https://user-images.githubusercontent.com/1214176/82652883-092fb300-9c27-11ea-9c69-ef48b745baee.png)
Since I've changed the relevant manually in my installation, I don't have an issue at the moment.
By the way, if I follow the link "view on npm" I can see the v1.3.0 there; the problem resides at Node-RED's side.

**Comment by ziflex** [comment]
I forgot to push 1.3.0 release 🤦‍♂️

**Comment by UNOPARATOR** [comment]
I guess you still haven't pushed the button yet.
Because after another month, it still shows the v1.2.0 as the latest version at https://flows.nodered.org/node/@node-red-tools/node-red-contrib-mongodb , which makes it impossible to update using the "Manage palette" menu. :(

**Comment by echoix** [comment]
Since April 2020, they can't update the flows from the npm. You need to login the [flows.nodered.org](flows.nodered.org) and press "Request refresh", or just resubmit it....
https://discourse.nodered.org/t/how-to-add-update-nodes-to-the-flow-library/25294

**Comment by echoix** [comment]
Looks like anyone connected with their Github account can request a refresh, I did it a couple minutes ago and seems bumped to 1.3.0!
![image](https://user-images.githubusercontent.com/27212526/87235642-2b82b900-c3ac-11ea-99e3-c1615735d9cb.png)

**Comment by UNOPARATOR** [comment]
Thank you @echoix . I would have never guessed loging in to Node-RED with my github account to be able to "request refresh".
