### ISSUE TITLE
Question :  Fetching data with a cursor or iteratively

### ISSUE THREAD

**Issue by BigJerBD** [node-red-tools/node-red-contrib-mongodb#30]
I'm using this package with a mongodb with a lot of data inside. 

Since I have to much data, to simply do a `find`  (node red simply end up freezing because of the size of the returned array) , I would like to know if there is a way to do a cursor based find so I can have a message for every document found in my database.

Thanks!

**Comment by ziflex** [comment]
Hey, thanks for using it!
Right now, cursor is not supported, but you can use pagination. The caveat tho, is that you will have to do it manually by creating a query object. 
Good feature request, btw :)

**Comment by BigJerBD** [comment]
(Closing the issue since question was answered) 

Sorry for not replying , thanks ! :)
